### ISSUE TITLE
Components development best practices

### ISSUE THREAD

**Issue by tperroin** [Talend/components#407]
Hello,

I'm new in the Talend community and, for our company, we need to create a set of components for a better integration of our ERP.

I have already started to develop components by following the Talend documentation about the _Component designer_ but without a real success (less flexibility that here).

That's why I'm here and I have followed the [Quickstart using Maven Archetype](https://github.com/Talend/components/wiki/Quickstart-using-Maven-Archetype). But I see that you are very active here and many changes are done.

So I have a few questions about the future of Talend components' development :

- Is there a roadmap for it? 
- How can we start developing with the last version of components-api?
- Is there a place for best practices and/or documentation?
- Is there guidelines to develop components like _SalesForce_ module type? 

For information our environment is : Talend Data Services Platform 6.2.1.

Thank you!

**Comment by sgandon** [comment]
Hello Thibault,
Thank you very much for this message. 
Indeed this project is very active because this is a rather recent project we have created for creating versatile components that may be used in the Studio as well as in other runtime such as apache beam.
The only technical documentation available right now can be found here on this repository wiki as well as some read-me file in the repo folders.
We are planning to release a 1.0 version this year which should be a stable version with a proper documentation.
If you want to support only you version you'll have to checkout this repos on the [maintenance/0.13](https://github.com/Talend/components/tree/maintenance/0.13) branch.
We are releasing new versions very often and we may break the APIs until we reach the 1.0 stage.

I hope this helps.

Feel free to contact me for more support.

SeB.

**Comment by tperroin** [comment]
Hello,

Thank you for your reply. I'm glad to hear that you have planned to release a 1.0 version this year.

I'm currently using the 0.13 branch as the quickstart guide said. And I'm OK with the APIs' break. 

It should be great to create a repository or at least a folder for the documentation with some examples and guidelines to create components. In fact, I'm coming from the Symfony (PHP framework) community and the documentation is THE most important to catch new developers. Of course, I will be very happy to contribute to the documentation.

Maybe it's not your ambition, and I understand that. You just have to say it.

Thank you again ! I keep you informed about my progress.

**Comment by tperroin** [comment]
I'm closing the issue for now. Waiting for a better documentation in the `1.0.0` version 👍
