### ISSUE TITLE
While running the job asking for the JAR file which is already supplied

### ISSUE THREAD

**Issue by adv-sunilsoni** [Talend/components#732]
I am creating the components for the Talend similar to Jira and Azure.

I got success in creating and installing the component into the TOS(Talend Studio), able edit the configuration of the installed components.
But while trying to run the job, Talend asks for the dependency which is jar generated during the POM packaging 

> **Tried to create simple component using the command and then build and installed the file input component in the Talend received the same jar issue**

>  **org.talend.components.trial-0.16.0.jar**

 I am using the bundle file

>  **org.talend.components.trial-0.16.0-bundle.jar**

 to install the components.

If I provide the  

> **org.talend.components.trial-0.16.0.jar**

 file, then job runs successfully, and if I don't provide the dependency then, TOS job gives the error 

> org.talend not found

Is there any solution by which I don't need to install the Jar file. because all classes of the jar are already supplied in the bundle jar.

**Comment by sgandon** [comment]
Hello, 
Sorry for not responding earlier;
did you manage to solve tour problem ?
if you run the job on the same machine as the one you developped your component with you can setup the Studio to use your global maven repository usually located in <user>/.m2 instead of the one provided with the Studio.
to do so have a look at the option 4 in this wiki page: https://github.com/Talend/components/wiki/8.-Testing-the-component-in-Talend-Studio

**Comment by sunilsoniudaipur** [comment]
Yes, for now, we are supplying the file manually and later will add it to some repository, 
Thanks for your help.
